### ISSUE TITLE
Wrong order of commands on chrooting for grub

### ISSUE THREAD

**Issue by benlk** [eustasy-archive/howtoubuntu.org-v1#11]
In the unmounting section of https://github.com/eustasy/howtoubuntu.org/blob/master/broadcast/how-to-repair-restore-reinstall-grub-2-with-a-ubuntu-live-cd.php , You must `umount /mnt/dev/pts/` _before_ `umount /mnt/dev/`. Doing it as currently written will result in an error, at least on the Ubuntu 12.04 live CD. 

The [Boot-Repair](https://help.ubuntu.com/community/Boot-Repair) tool is of great use, and may be an asset in this tutorial.

**Comment by lewisgoddard** [comment]
You are quite right, in fact I have reversed the ordering for all the unmounts, as they should have been. As to Boot-Repair, I have found it finicky and unsupportive in far too many situations. I would prefer users have more knowledge of what is failing, rather than a generic error.
