### ISSUE TITLE
Thing Trusty Chrome Install Script 32 v 64

### ISSUE THREAD

**Issue by mdwy62** [eustasy-archive/howtoubuntu.org-v1#15]
I just did a fresh install of 14.04 64 bit, but the chrome install script installed 32 bit chrome.

**Comment by lewisgoddard** [comment]
Could you post the output of `getconf LONG_BIT` here please?

**Comment by mdwy62** [comment]
Sure. Thanks for the post. All the other steps worked great!

mark@md-ins1420:~$ getconf LONG_BIT
64

I am attaching the script. Maybe I did not copy it properly?

I am about to use the software center to install 
google-chrome-stable_current_amd64.deb

Is this different from the chromium-browser available in synaptic? I 
already have the latter installed.
Version 36.0.1985.125 Ubuntu 14.04 (283153)

**Comment by lewisgoddard** [comment]
Chromium Browser in Synaptic is pure Chromium, and does not include the Pepper Flash plugin or Google branding as Chrome does.

The script and that result looks fine, are you sure it stated it was installing the 32bit version? It should have said "32bit Detected" on it's own line after you hit enter.

**Comment by mdwy62** [comment]
Yes, it did. I was surprised and dismayed. It installed the i386 version.

Thanks for explaining the differences in the browsers.

I used dpkg to uninstall the i386 version and then wget from your script 
to download the 64 bit version (amd64). It installed and seems to be 
working fine.

I thought I might have figured it out. I may have been running the 
script in a shell I opened under mc (midnight commander) with ctl-o. But 
yesterday I ran |getconf LONG_BIT in the same shell (under midnight 
commander) and it reported 64 as well.
|

On August 18, 2014 1:20:54 AM PDT, Lewis Goddard 
notifications@github.com wrote:

```
Chromium Browser in Synaptic is pure Chromium, and does not include
the Pepper Flash plugin or Google branding as Chrome does.

The script and that result looks fine, are you sure it stated it was
installing the 32bit version? It should have said "32bit Detected"
on it's own line after you hit enter.

—
Reply to this email directly or view it on GitHub
<https://github.com/eustasy/howtoubuntu.org/issues/15#issuecomment-52463781>.
```

**Comment by lewisgoddard** [comment]
Hm, maybe Midnight Commander is behaving badly with the syntax. Can you try it in the normal terminal for Ubuntu?

**Comment by lewisgoddard** [comment]
Closed due to lack of activity.
