### ISSUE TITLE
Very Minor issue in howtoubuntu.org/things-to-do-after-installing-ubuntu-14-04-trusty-tahr

### ISSUE THREAD

**Issue by apsamuel** [eustasy-archive/howtoubuntu.org-v1#16]
http://howtoubuntu.org/things-to-do-after-installing-ubuntu-14-04-trusty-tahr
- In #9 Installing Google Chrome, the bash code block won't run, it is missing the 'fi' keyword to complete the statement.

Nice article!!

**Comment by lewisgoddard** [comment]
Really? I see the code block ending with `fi`.  
Are you sure you copied it all?

```
if [[ $(getconf LONG_BIT) = "64" ]]
then
    echo "64bit Detected" &&
    echo "Installing Google Chrome" &&
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&
    sudo dpkg -i google-chrome-stable_current_amd64.deb &&
    rm -f google-chrome-stable_current_amd64.deb
else
    echo "32bit Detected" &&
    echo "Installing Google Chrome" &&
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb &&
    sudo dpkg -i google-chrome-stable_current_i386.deb &&
    rm -f google-chrome-stable_current_i386.deb
fi
```

**Comment by apsamuel** [comment]
apologies - i didn't notice the content box was 'scrollable'.

Kind Regards,
Aaron Peter Samuel
Enterprise Solutions Expert
Specialties: Unix/Linux, Networking, Applications, Storage
Profile: http://www.google.com/profiles/aaron.psamuel
References: http://www.linkedin.com/in/aaronpsamuel

If you aren't proud of it, it isn't good enough.
