### ISSUE TITLE
"libdvdcss" no install candidate

### ISSUE THREAD

**Issue by TamaMcGlinn** [eustasy-archive/howtoubuntu.org-v1#23]
There is a problem following the instructions below, which would not very easily be solved by new Ubuntu users. libdvdcss does not seem to exist in Ubuntu, so the apt-get line outputs `"libdvdcss" has no installation candidate"` 
Please mention this can happen, and link the help-forum topic directly.

http://howtoubuntu.org/how-to-play-a-dvd-in-ubuntu
libdvdcss has no installation candidate, but
https://help.ubuntu.com/community/RestrictedFormats/PlayingDVDs
says do:
sudo /usr/share/doc/libdvdread4/install-css.sh

And I can confirm it works afterwards in Ubuntu 14.04 LTS with VLC media player 2.1.4 Rincewind (revision 2.1.4-0-g2a072be)

**Comment by lewisgoddard** [comment]
You shouldn't need to run `sudo /usr/share/doc/libdvdread4/install-css.sh` manually, `dpkg` does it automatically after the package is installed. As for the installation candidate, I will have to build a fresh machine to test.

**Comment by TamaMcGlinn** [comment]
I will be installing 14.04 LTS fresh on a laptop within a few days, and will test this issue again and let you know.
